replicaCount: 1
nameOverride: florestad
image:
  repository: gustavostingelin/floresta
  pullPolicy: IfNotPresent

florestad:
  network: bitcoin
  dataDir: /data
  toml: |
    [wallet]
    xpubs = []
    descriptors = []
    addresses = []

service:
  type: ClusterIP
  rpc:
    port: 8332
  electrum:
    port: 50001
  metrics:
    port: 3333

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

livenessProbe:
  tcpSocket:
    port: electrum
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: electrum
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

imagePullSecrets: []
podAnnotations: {}
podLabels: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
