apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "florestad-chart.fullname" . }}-config
  labels:
    {{- include "florestad-chart.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.florestad.toml | nindent 4 }}
