apiVersion: v1
kind: Service
metadata:
  name: {{ include "florestad-chart.fullname" . }}
  labels:
    {{- include "florestad-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpc.port }}
      targetPort: rpc
    - name: electrum
      port: {{ .Values.service.electrum.port }}
      targetPort: electrum
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
  selector:
    {{- include "florestad-chart.selectorLabels" . | nindent 4 }}
