apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "florestad-chart.fullname" . }}
  labels:
    {{- include "florestad-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "florestad-chart.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "florestad-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "florestad-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "florestad-chart.name" . }}
          image: {{ include "florestad-chart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rpc
              containerPort: 8332
            - name: electrum
              containerPort: 50001
            - name: metrics
              containerPort: 3333
          command:
            - florestad
          args:
            - "-c"
            - "/config/config.toml"
            - "--network"
            - "{{ .Values.florestad.network }}"
            - "--data-dir"
            - "{{ .Values.florestad.dataDir }}"
          volumeMounts:
            - name: data
              mountPath: {{ .Values.florestad.dataDir }}
            - name: config
              mountPath: /config
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "florestad-chart.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
